#!/bin/bash
set -euo pipefail

echo '--- :house_with_garden: Setting up the environment via pre-command hook from .buildkite/hooks/pre-command'
export USER='PRE-JohnDoe'
export PASSWORD='PRE-Welcome@123'
